# Generated by Django 6.0.4 on 2026-04-17 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='corporation',
            fields=[
                ('corp_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=100)),
                ('stock_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('modify_date', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='filings',
            fields=[
                ('corp_cls', models.CharField(choices=[('Y', '유가'), ('K', '코스닥'), ('N', '코넥스'), ('E', '기타')], max_length=1)),
                ('rcept_no', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('report_nm', models.TextField()),
                ('rcept_dt', models.CharField(max_length=8)),
                ('rm', models.TextField(blank=True, null=True)),
                ('corp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp_manager.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='financial_statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reprt_code', models.CharField(choices=[(11013, '1분기보고서'), (11012, '반기보고서'), (11014, '3분기보고서'), (11011, '사업보고서')], max_length=5)),
                ('bsns_year', models.CharField(max_length=4)),
                ('sj_div', models.CharField(choices=[('BS', '재무상태표'), ('IS', '손익계산서'), ('CIS', '포괄손익계산서'), ('CF', '현금흐름표'), ('SCE', '자본변동표')], max_length=3)),
                ('sj_nm', models.TextField()),
                ('account_id', models.CharField(default='-표준계정코드 미사용-', max_length=100)),
                ('account_nm', models.CharField(max_length=100)),
                ('account_detail', models.TextField(default='-')),
                ('thstrm_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('thstrm_amount', models.BigIntegerField(blank=True, null=True)),
                ('thstrm_add_amount', models.BigIntegerField(blank=True, null=True)),
                ('frmtrm_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('frmtrm_amount', models.BigIntegerField(blank=True, null=True)),
                ('frmtrm_q_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('frmtrm_q_amount', models.BigIntegerField(blank=True, null=True)),
                ('frmtrm_add_amount', models.BigIntegerField(blank=True, null=True)),
                ('bfefrmtrm_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('bfefrmtrm_amount', models.BigIntegerField(blank=True, null=True)),
                ('ord', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('corp_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp_manager.corporation')),
                ('rcept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corp_manager.filings')),
            ],
            options={
                'unique_together': {('rcept_no', 'sj_div', 'account_id', 'account_nm')},
            },
        ),
        migrations.DeleteModel(
            name='Corpration',
        ),
    ]
